### ISSUE TITLE
Vulnerability to retiring spatial infrastructure packages

### ISSUE THREAD

**Issue by rsbivand** [kjschmidlab/GGoutlieR#1]
For background see: https://r-spatial.org/r/2023/05/15/evolution4.html and https://r-spatial.github.io/evolution/. This package imports `sp`, but this month `sp` will switch to relying on `sf` in place of `rgdal` to access upstream external software. When running forthcoming `sp` and without retiring packages on the library path, the CMD check log file is:
[00check.log](https://github.com/kjschmidlab/GGoutlieR/files/11744444/00check.log) with install failure 
[00install.zip](https://github.com/kjschmidlab/GGoutlieR/files/11744449/00install.zip) cause by importing `rworldmap`, which imports `maptools`. Once `rworldmap` is updated https://github.com/AndySouth/rworldmap/issues/20, you may need to add `sf` to Suggests:.

**Comment by CheWeiChang1992** [comment]
The calculation of geographical distance with `geosphere` is now replaced with `sf`.
`rworldmap` used in the plotting function is now replaced with `rnaturalearth`.

**Comment by rsbivand** [comment]
@CheWeiChang1992 CMD check output without retiring packages on library path: 
[00check.log](https://github.com/kjschmidlab/GGoutlieR/files/12854247/00check.log)

Quite a lot of undefined global functions or variables:
```
  aes coord_sf element_rect element_text geom_point geom_segment
  guide_legend guides labs logp scale_fill_manual scale_linewidth theme
  type value x x0 x1 y y0 y1
```
They look like missing import declarations possibly from `ggplot2`. Otherwise good to go, I think.

**Comment by CheWeiChang1992** [comment]
> @CheWeiChang1992 CMD check output without retiring packages on library path: [00check.log](https://github.com/kjschmidlab/GGoutlieR/files/12854247/00check.log)
> 
> Quite a lot of undefined global functions or variables:
> 
> ```
>   aes coord_sf element_rect element_text geom_point geom_segment
>   guide_legend guides labs logp scale_fill_manual scale_linewidth theme
>   type value x x0 x1 y y0 y1
> ```
> 
> They look like missing import declarations possibly from `ggplot2`. Otherwise good to go, I think.

Thank you for helping with checking the package.
I added the `import` commands in `NAMESPACE` and used `ggplot2::.data` for calling variables from data in making `ggplot`.
The `GGoutlieR_1.0.1.tar.gz` has been submitted to CRAN.

**Comment by rsbivand** [comment]
@CheWeiChang1992 Thanks for your cooperation!
