### ISSUE TITLE
[JOSS REVIEW] Add community guidelines docs

### ISSUE THREAD

**Issue by tkchafin** [kjschmidlab/GGoutlieR#2]
- Add instruction on how you would like users to seek support/ report problems in the README.Md (usually this is just linking to the Issues page) 
- Add instructions on how to contribute

**Comment by CheWeiChang1992** [comment]
> * Add instruction on how you would like users to seek support/ report problems in the README.Md (usually this is just linking to the Issues page)
> * Add instructions on how to contribute

Thank you for the suggestion. We included the instruction of "Contributing" to the README.md.
